import Link from "next/link";
import { BarChart3, BookOpenCheck, CalendarDays, CircleDot, GraduationCap, Megaphone, UserPlus, UsersRound } from "lucide-react";

import {
  addCohortMemberAction,
  createCohortAnnouncementAction,
  createCohortAssignmentAction,
  createCohortEventAction,
  duplicateCohortAction,
  generatePeerReviewsAction,
  markCohortAttendanceAction,
  transitionCohortAction,
  updateCohortMemberStatusAction,
  updateCohortEventAction,
} from "@/actions/cohorts";
import type { getCohortOperationsDashboard } from "@/lib/services/cohort-management.service";
import { ProjectReviewPanel } from "@/components/dashboard/admin/ProjectReviewPanel";

type OperationsData = NonNullable<Awaited<ReturnType<typeof getCohortOperationsDashboard>>>;

const field = "h-11 w-full rounded-xl border border-[#D9E0EC] bg-white px-3 text-sm text-[#071535] outline-none transition focus:border-[#1C4ED1] focus:ring-2 focus:ring-[#1C4ED1]/10";
const textarea = `${field} h-auto min-h-24 py-3`;

function count(rows: Array<{ status: string; _count: { status: number } }>, status: string) {
  return rows.find((row) => row.status === status)?._count.status ?? 0;
}

function dt(value: Date) {
  return new Date(value).toLocaleString("en-GB", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" });
}

function Section({ title, eyebrow, children }: { title: string; eyebrow: string; children: React.ReactNode }) {
  return <section className="rounded-[22px] border border-[#DFE5F0] bg-white shadow-[0_18px_50px_rgba(11,28,68,0.05)]"><header className="border-b border-[#ECF0F6] px-5 py-5 sm:px-6"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-[#1C4ED1]">{eyebrow}</p><h2 className="mt-2 text-xl font-black tracking-[-0.03em] text-[#071535]">{title}</h2></header><div className="p-5 sm:p-6">{children}</div></section>;
}

export function CohortOperationsConsole({ data, adminMode, returnTo, message }: { data: OperationsData; adminMode: boolean; returnTo: string; message?: { kind: "success" | "error"; text: string } | null }) {
  const { cohort } = data;
  const learners = cohort.memberships.filter((item) => item.role === "LEARNER");
  const activeLearners = learners.filter((item) => item.status === "ACTIVE");
  const attended = count(data.attendance, "ATTENDED");
  const missed = count(data.attendance, "MISSED");
  const attendanceRate = attended + missed ? Math.round((attended / (attended + missed)) * 100) : 0;
  const submitted = count(data.submissions, "SUBMITTED") + count(data.submissions, "UNDER_REVIEW") + count(data.submissions, "APPROVED");
  const peerDone = count(data.peerReviews, "SUBMITTED");

  return (
    <main className="mx-auto max-w-[1680px] space-y-6 p-[clamp(16px,2.78vw,48px)] pb-28 font-jakarta">
      <header className="relative overflow-hidden rounded-[26px] bg-[#071535] px-6 py-7 text-white sm:px-8 sm:py-9">
        <div className="absolute -right-12 -top-20 h-56 w-56 rounded-full border-[32px] border-[#2E63EA]/25" aria-hidden="true" />
        <div className="relative flex flex-col gap-6 xl:flex-row xl:items-end xl:justify-between">
          <div><p className="text-[11px] font-black uppercase tracking-[0.18em] text-[#87A8FF]">{cohort.program.school.name} · Cohort operations</p><h1 className="mt-3 text-3xl font-black tracking-[-0.045em] sm:text-4xl">{cohort.title}</h1><p className="mt-2 text-sm font-semibold text-[#B7C7E8]">{cohort.program.title} · {cohort.status.toLowerCase().replaceAll("_", " ")}</p></div>
          <div className="flex flex-wrap gap-3"><Link href={`/dashboard/cohorts/${cohort.slug}`} className="rounded-full border border-white/20 bg-white/10 px-5 py-2.5 text-sm font-black">Preview student view</Link>{adminMode ? <Link href="/dashboard/admin/cohorts" className="rounded-full bg-white px-5 py-2.5 text-sm font-black text-[#071535]">All cohorts</Link> : <Link href="/dashboard/instructor/cohorts" className="rounded-full bg-white px-5 py-2.5 text-sm font-black text-[#071535]">Assigned cohorts</Link>}</div>
        </div>
      </header>

      {message ? <div role="status" className={`rounded-2xl border px-5 py-4 text-sm font-bold ${message.kind === "success" ? "border-emerald-200 bg-emerald-50 text-emerald-800" : "border-red-200 bg-red-50 text-red-800"}`}>{message.text}</div> : null}

      <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">
        {[
          { label: "Active learners", value: `${activeLearners.length}/${cohort.capacity}`, Icon: UsersRound },
          { label: "Attendance", value: `${attendanceRate}%`, Icon: CalendarDays },
          { label: "Submissions", value: submitted, Icon: BookOpenCheck },
          { label: "Peer reviews", value: peerDone, Icon: GraduationCap },
          { label: "Quiz average", value: `${Math.round(data.quizAttempts._avg.percentage ?? 0)}%`, Icon: BarChart3 },
        ].map(({ label, value, Icon }) => <article key={label} className="rounded-[18px] border border-[#E1E7F0] bg-white p-5"><Icon className="text-[#1C4ED1]" size={19} /><p className="mt-4 text-[11px] font-black uppercase tracking-[0.12em] text-[#8490A6]">{label}</p><p className="mt-1 text-2xl font-black text-[#071535]">{value}</p></article>)}
      </section>

      {adminMode ? <Section eyebrow="Lifecycle" title="Governance controls"><div className="grid gap-5 xl:grid-cols-[1fr_1.2fr]"><div><p className="text-sm leading-6 text-[#64718A]">Only cohort admins can change admissions or lifecycle state. Destructive transitions are audit logged.</p><div className="mt-4 flex flex-wrap gap-2">{(["APPLICATIONS_OPEN", "APPLICATIONS_CLOSED", "IN_PROGRESS", "COMPLETED", "CANCELLED", "ARCHIVED"] as const).map((status) => <form key={status} action={transitionCohortAction}><input type="hidden" name="cohortSlug" value={cohort.slug}/><input type="hidden" name="returnTo" value={returnTo}/><input type="hidden" name="status" value={status}/><button className="rounded-full border border-[#D9E0EC] px-3 py-2 text-xs font-black text-[#42516A] hover:border-[#1C4ED1] hover:text-[#1C4ED1]">{status.toLowerCase().replaceAll("_", " ")}</button></form>)}</div></div><form action={addCohortMemberAction} className="grid gap-3 rounded-2xl bg-[#F5F8FD] p-4 sm:grid-cols-[1fr_180px_auto]"><input type="hidden" name="cohortSlug" value={cohort.slug}/><input type="hidden" name="returnTo" value={returnTo}/><label className="grid gap-1 text-xs font-black text-[#667085]">Account email<input name="email" type="email" required className={field}/></label><label className="grid gap-1 text-xs font-black text-[#667085]">Cohort role<select name="role" className={field}><option value="LEARNER">Learner</option><option value="INSTRUCTOR">Instructor</option><option value="TEACHING_ASSISTANT">Teaching assistant</option><option value="MENTOR">Mentor</option></select></label><button className="self-end rounded-xl bg-[#1C4ED1] px-4 py-3 text-sm font-black text-white"><UserPlus className="mr-2 inline" size={15}/>Add</button></form></div></Section> : null}

      {adminMode ? <div className="grid gap-6 xl:grid-cols-2"><Section eyebrow="Reuse" title="Duplicate cohort structure"><form action={duplicateCohortAction} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="cohortSlug" value={cohort.slug}/><input type="hidden" name="returnTo" value={returnTo}/><input name="title" required placeholder="New cohort title" className={field}/><input name="slug" placeholder="new-cohort-slug" className={field}/><label className="grid gap-1 text-xs font-black text-[#667085]">Applications open<input name="applicationOpenAt" type="datetime-local" required className={field}/></label><label className="grid gap-1 text-xs font-black text-[#667085]">Applications close<input name="applicationCloseAt" type="datetime-local" required className={field}/></label><label className="grid gap-1 text-xs font-black text-[#667085]">Starts<input name="startsAt" type="datetime-local" required className={field}/></label><label className="grid gap-1 text-xs font-black text-[#667085]">Ends<input name="endsAt" type="datetime-local" required className={field}/></label><button className="rounded-xl bg-[#071535] px-5 py-3 text-sm font-black text-white sm:col-span-2">Duplicate staff, assignments, and rubrics</button></form></Section><Section eyebrow="Access" title="Membership status"><div className="max-h-[360px] space-y-2 overflow-auto">{cohort.memberships.map((member) => <form key={member.id} action={updateCohortMemberStatusAction} className="grid grid-cols-[1fr_130px_auto] items-center gap-2 rounded-xl bg-[#F6F8FC] p-2"><input type="hidden" name="cohortSlug" value={cohort.slug}/><input type="hidden" name="returnTo" value={returnTo}/><input type="hidden" name="membershipId" value={member.id}/><div className="min-w-0 pl-2"><p className="truncate text-xs font-black text-[#071535]">{member.user.name ?? member.user.email}</p><p className="text-[10px] font-bold uppercase text-[#8A96AA]">{member.role.toLowerCase().replaceAll("_", " ")}</p></div><select name="membershipStatus" defaultValue={member.status} className="h-9 rounded-lg border border-[#D9E0EC] bg-white px-2 text-[11px]"><option value="ACTIVE">Active</option><option value="PAUSED">Paused</option><option value="COMPLETED">Completed</option><option value="WITHDRAWN">Withdrawn</option></select><button className="h-9 rounded-lg bg-[#1C4ED1] px-3 text-[10px] font-black text-white">Save</button></form>)}</div></Section></div> : null}

      <div className="grid gap-6 2xl:grid-cols-2">
        <Section eyebrow="Live learning" title="Schedule a cohort event"><form action={createCohortEventAction} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="cohortSlug" value={cohort.slug}/><input type="hidden" name="returnTo" value={returnTo}/><input name="title" required placeholder="Session title" className={`${field} sm:col-span-2`}/><select name="type" className={field}><option value="LIVE_SESSION">Live class</option><option value="MENTORSHIP">Office hours</option><option value="EXAM">Exam</option><option value="DEADLINE">Deadline</option></select><input name="timezone" defaultValue={cohort.timezone} className={field}/><label className="grid gap-1 text-xs font-black text-[#667085]">Starts<input name="startsAt" type="datetime-local" required className={field}/></label><label className="grid gap-1 text-xs font-black text-[#667085]">Ends<input name="endsAt" type="datetime-local" className={field}/></label><input name="meetingUrl" type="url" placeholder="Meeting URL" className={`${field} sm:col-span-2`}/><textarea name="description" placeholder="What students should prepare" className={`${textarea} sm:col-span-2`}/><button className="rounded-xl bg-[#1C4ED1] px-5 py-3 text-sm font-black text-white sm:col-span-2">Schedule and notify learners</button></form></Section>

        <Section eyebrow="Assessment" title="Create an assignment"><form action={createCohortAssignmentAction} className="grid gap-3 sm:grid-cols-2"><input type="hidden" name="cohortSlug" value={cohort.slug}/><input type="hidden" name="returnTo" value={returnTo}/><input name="title" required placeholder="Assignment title" className={field}/><input name="slug" placeholder="assignment-slug" className={field}/><select name="assignmentType" className={field}><option value="PROJECT">Project</option><option value="PRACTICE">Practice</option><option value="REFLECTION">Reflection</option><option value="CAPSTONE">Capstone</option></select><select name="latePolicy" className={field}><option value="MARK_LATE">Accept and mark late</option><option value="ALLOW">Accept late</option><option value="BLOCK">Block late work</option></select><label className="grid gap-1 text-xs font-black text-[#667085]">Release<input name="releaseAt" type="datetime-local" className={field}/></label><label className="grid gap-1 text-xs font-black text-[#667085]">Due<input name="dueAt" type="datetime-local" className={field}/></label><textarea name="brief" required placeholder="Assignment brief" className={`${textarea} sm:col-span-2`}/><textarea name="deliverables" placeholder={'One deliverable per line'} className={textarea}/><textarea name="rubric" required placeholder={'Criterion title | Description | 5\nClarity | Communicates decisions | 5'} className={textarea}/><div className="sm:col-span-2 grid gap-3 rounded-2xl bg-[#F5F8FD] p-4 sm:grid-cols-3"><label className="text-xs font-black text-[#667085]">Maximum score<input name="maxScore" type="number" min="1" defaultValue="100" className={`${field} mt-1`}/></label><label className="text-xs font-black text-[#667085]">Reviews / learner<input name="peerReviewsPerLearner" type="number" min="1" max="5" defaultValue="2" className={`${field} mt-1`}/></label><label className="text-xs font-black text-[#667085]">Review due<input name="peerReviewDueAt" type="datetime-local" className={`${field} mt-1`}/></label><label className="flex items-center gap-2 text-xs font-black text-[#42516A]"><input name="peerReviewEnabled" type="checkbox"/> Peer review</label><label className="flex items-center gap-2 text-xs font-black text-[#42516A]"><input name="showcaseEligible" type="checkbox" defaultChecked/> Showcase eligible</label><label className="flex items-center gap-2 text-xs font-black text-[#42516A]"><input name="publishNow" type="checkbox" defaultChecked/> Publish now</label></div><div className="sm:col-span-2 flex flex-wrap gap-4 text-xs font-bold text-[#526078]">{["TEXT", "FILE", "URL", "REPOSITORY"].map((format) => <label key={format} className="flex items-center gap-2"><input type="checkbox" name="submissionFormats" value={format} defaultChecked={format !== "FILE"}/>{format.toLowerCase()}</label>)}</div><button className="rounded-xl bg-[#071535] px-5 py-3 text-sm font-black text-white sm:col-span-2">Create assignment</button></form></Section>

        <Section eyebrow="Communication" title="Publish an announcement"><form action={createCohortAnnouncementAction} className="grid gap-3"><input type="hidden" name="cohortSlug" value={cohort.slug}/><input type="hidden" name="returnTo" value={returnTo}/><input name="title" required placeholder="Announcement title" className={field}/><textarea name="body" required placeholder="Message for the cohort" className={textarea}/><div className="flex gap-3"><input name="priority" type="number" min="0" max="10" defaultValue="0" aria-label="Priority" className={`${field} max-w-28`}/><button className="flex-1 rounded-xl bg-[#1C4ED1] px-5 py-3 text-sm font-black text-white"><Megaphone className="mr-2 inline" size={15}/>Publish and notify</button></div></form></Section>

        <Section eyebrow="Roster" title={`${cohort.memberships.length} cohort members`}><div className="max-h-[430px] divide-y divide-[#EDF1F6] overflow-auto">{cohort.memberships.map((member) => <div key={member.id} className="flex items-center justify-between gap-4 py-3"><div className="min-w-0"><p className="truncate text-sm font-black text-[#071535]">{member.user.name ?? member.user.email}</p><p className="mt-1 text-[11px] font-bold uppercase tracking-[0.1em] text-[#8A96AA]">{member.role.toLowerCase().replaceAll("_", " ")}</p></div><span className="rounded-full bg-[#F0F4FA] px-3 py-1 text-[10px] font-black uppercase text-[#526078]">{member.status}</span></div>)}</div></Section>
      </div>

      <Section eyebrow="Run of show" title="Events, recordings, and attendance"><div className="space-y-4">{cohort.scheduleEvents.length ? cohort.scheduleEvents.map((event) => <article key={event.id} className="rounded-2xl border border-[#E1E7F0] p-4 sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><div className="flex items-center gap-2"><CircleDot className={event.status === "LIVE" ? "text-red-500" : "text-[#1C4ED1]"} size={16}/><p className="text-sm font-black text-[#071535]">{event.title}</p></div><p className="mt-2 text-xs font-bold text-[#7B879D]">{dt(event.startsAt)} · {event.status.toLowerCase()} · {event._count.attendees} attendees</p></div><form action={updateCohortEventAction} className="flex flex-wrap gap-2"><input type="hidden" name="cohortSlug" value={cohort.slug}/><input type="hidden" name="returnTo" value={returnTo}/><input type="hidden" name="eventId" value={event.id}/><select name="status" defaultValue={event.status} className={`${field} w-36`}><option value="SCHEDULED">Scheduled</option><option value="LIVE">Live</option><option value="COMPLETED">Completed</option><option value="CANCELLED">Cancelled</option></select><input name="recordingUrl" type="url" defaultValue={event.recordingUrl ?? ""} placeholder="Recording URL" className={`${field} min-w-52 flex-1`}/><button className="rounded-xl bg-[#071535] px-4 text-xs font-black text-white">Update</button></form></div>{event.attendees.length ? <details className="mt-4"><summary className="cursor-pointer text-xs font-black text-[#1C4ED1]">Mark attendance</summary><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{event.attendees.map((attendee) => <form key={attendee.id} action={markCohortAttendanceAction} className="flex items-center gap-2 rounded-xl bg-[#F6F8FC] p-2"><input type="hidden" name="cohortSlug" value={cohort.slug}/><input type="hidden" name="returnTo" value={returnTo}/><input type="hidden" name="eventId" value={event.id}/><input type="hidden" name="userId" value={attendee.user.id}/><span className="min-w-0 flex-1 truncate text-xs font-bold text-[#42516A]">{attendee.user.name ?? attendee.user.email}</span><select name="attendanceStatus" defaultValue={attendee.status} className="h-8 rounded-lg border border-[#D9E0EC] bg-white px-2 text-[11px]"><option value="INVITED">Invited</option><option value="REGISTERED">Registered</option><option value="ATTENDED">Attended</option><option value="MISSED">Missed</option><option value="CANCELLED">Cancelled</option></select><button aria-label="Save attendance" className="h-8 rounded-lg bg-[#1C4ED1] px-2 text-[10px] font-black text-white">Save</button></form>)}</div></details> : null}</article>) : <p className="rounded-2xl border border-dashed border-[#CCD5E3] p-8 text-center text-sm font-semibold text-[#7B879D]">No cohort events yet.</p>}</div></Section>

      <Section eyebrow="Peer learning" title="Assignments, grading, and review rounds"><div className="grid gap-3 lg:grid-cols-2">{cohort.projects.map((project) => <article key={project.id} className="rounded-2xl border border-[#E1E7F0] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm font-black text-[#071535]">{project.title}</p><p className="mt-1 text-xs font-semibold text-[#7B879D]">{project.assignmentType.toLowerCase()} · {project._count.submissions} submissions · {project._count.peerReviewAssignments} reviews</p></div><span className="rounded-full bg-[#F0F4FA] px-2.5 py-1 text-[10px] font-black text-[#526078]">{project.status}</span></div>{project.peerReviewEnabled ? <form action={generatePeerReviewsAction} className="mt-4"><input type="hidden" name="cohortSlug" value={cohort.slug}/><input type="hidden" name="returnTo" value={returnTo}/><input type="hidden" name="projectId" value={project.id}/><button className="rounded-full border border-[#1C4ED1] px-3 py-2 text-xs font-black text-[#1C4ED1]">Assign pending peer reviews</button></form> : null}{project.submissions.map((submission) => <details key={submission.id} className="mt-4 rounded-xl bg-[#F6F8FC] p-4"><summary className="cursor-pointer text-xs font-black text-[#071535]">Grade {submission.user.name ?? submission.user.email} · v{submission.currentVersion}</summary><p className="mt-3 text-xs leading-5 text-[#64718A]">{submission.summary}</p><div className="mt-4 border-t border-[#E1E7F0] pt-4"><ProjectReviewPanel submissionId={submission.id} criteria={project.rubricCriteria} canPublish={project.showcaseEligible && submission.showcaseConsent}/></div></details>)}</article>)}{!cohort.projects.length ? <p className="text-sm text-[#7B879D]">No assignments created.</p> : null}</div></Section>
    </main>
  );
}
