import { Building2, CreditCard, FileText, UsersRound } from "lucide-react";

import { createOrganizationCohortAction, issueOrganizationInvoiceAction, markOrganizationInvoicePaidAction, setOrganizationStatusAction } from "@/actions/organizations";
import { requireAnyAdminPermission } from "@/lib/admin-guards";
import { getAdminOrganizations } from "@/lib/services/organization.service";

export const metadata = { title: "Organizations | CSCN Admin" };

function money(value: number | string, currency: string) {
  return new Intl.NumberFormat("en-NG", { style: "currency", currency, maximumFractionDigits: 0 }).format(Number(value));
}

export default async function AdminOrganizationsPage() {
  await requireAnyAdminPermission(["canManageBilling", "canManageUsers", "canViewAnalytics"]);
  const data = await getAdminOrganizations();
  const active = data.organizations.filter((item) => item.status === "ACTIVE").length;
  const members = data.organizations.reduce((sum, item) => sum + item._count.members, 0);
  return <main className="mx-auto max-w-[1600px] space-y-6 p-[clamp(16px,2.5vw,42px)] pb-28 text-[#071535]"><header className="rounded-[26px] bg-[#071535] p-7 text-white md:p-10"><p className="text-xs font-black uppercase tracking-[.15em] text-[#E8B44E]">Organization operations</p><h1 className="mt-3 text-4xl font-black tracking-[-.055em]">Team learning, with a clear access boundary.</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-[#C0CBE0]">Verify workspaces, quote seat packages, confirm manual invoice payment, and monitor capacity without exposing private learner activity.</p><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white/8 p-4"><Building2 size={18}/><p className="mt-4 text-2xl font-black">{active}</p><p className="text-xs text-[#AFC0DE]">active organizations</p></div><div className="rounded-2xl bg-white/8 p-4"><UsersRound size={18}/><p className="mt-4 text-2xl font-black">{members}</p><p className="text-xs text-[#AFC0DE]">organization members</p></div><div className="rounded-2xl bg-white/8 p-4"><FileText size={18}/><p className="mt-4 text-2xl font-black">{data.invoices.length}</p><p className="text-xs text-[#AFC0DE]">invoices awaiting confirmation</p></div></div></header>

    <section className="rounded-[22px] border border-[#E0E5EF] bg-white p-5 md:p-6"><h2 className="text-2xl font-black">Organization review</h2><div className="mt-5 divide-y divide-[#EDF0F5]">{data.organizations.map((organization) => <div key={organization.id} className="flex flex-col justify-between gap-4 py-5 lg:flex-row lg:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="font-black">{organization.name}</p><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${organization.status === "ACTIVE" ? "bg-[#E8F8EE] text-[#137A3E]" : organization.status === "PENDING_REVIEW" ? "bg-[#FFF5D8] text-[#8A6509]" : "bg-[#F1F3F6] text-[#667085]"}`}>{organization.status.replaceAll("_", " ")}</span></div><p className="mt-1 text-xs text-[#77839A]">{organization.type.toLowerCase()} · {organization.country || "Country not supplied"} · requested by {organization.requestedBy?.name || organization.requestedBy?.email || "CSCN admin"}</p><p className="mt-2 text-xs font-bold text-[#526078]">{organization._count.members} members · {organization._count.teams} teams · {organization._count.seatPackages} seat packages · {organization._count.invoices} invoices</p></div><form action={setOrganizationStatusAction} className="flex flex-wrap gap-2"><input type="hidden" name="organizationId" value={organization.id}/>{organization.status !== "ACTIVE" && <button name="status" value="ACTIVE" className="rounded-lg bg-[#1C4ED1] px-3 py-2 text-xs font-black text-white">Approve</button>}{organization.status === "ACTIVE" && <button name="status" value="SUSPENDED" className="rounded-lg border border-[#E2B8B1] px-3 py-2 text-xs font-black text-[#A33]">Suspend</button>}<button name="status" value="ARCHIVED" className="rounded-lg border border-[#D9DFE9] px-3 py-2 text-xs font-black">Archive</button></form></div>)}</div></section>

    <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-[22px] border border-[#E0E5EF] bg-white p-5 md:p-6"><div className="flex items-center gap-3"><CreditCard className="text-[#1C4ED1]"/><h2 className="text-2xl font-black">Seat quote queue</h2></div><div className="mt-5 space-y-4">{data.seatPackages.map((item) => <article key={item.id} className="rounded-2xl border border-[#E3E7EF] p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.08em] text-[#77839A]">{item.organization.name} · {item.status}</p><h3 className="mt-2 font-black">{item.program?.title || item.cohort?.program.title}</h3><p className="mt-1 text-xs text-[#667085]">{item.quantity} seats{item.cohort ? ` · ${item.cohort.title}` : ""}</p></div>{item.invoice && <span className="rounded-full bg-[#EEF3FF] px-3 py-1 text-[10px] font-black text-[#1C4ED1]">{item.invoice.number}</span>}</div>{item.notes && <p className="mt-3 rounded-xl bg-[#F7F9FC] p-3 text-xs leading-5 text-[#667085]">{item.notes}</p>}<form action={issueOrganizationInvoiceAction} className="mt-4 grid grid-cols-[1fr_1fr_auto] gap-2"><input type="hidden" name="seatPackageId" value={item.id}/><input name="pricePerSeat" type="number" min={0} step="0.01" required defaultValue={Number(item.pricePerSeat)} aria-label="Price per seat" placeholder="Price per seat" className="h-10 min-w-0 rounded-lg border border-[#D9DFE9] px-3 text-xs"/><input name="dueAt" type="date" aria-label="Invoice due date" className="h-10 min-w-0 rounded-lg border border-[#D9DFE9] px-2 text-xs"/><button className="rounded-lg bg-[#071535] px-3 text-xs font-black text-white">{item.invoice ? "Reissue" : "Issue invoice"}</button></form></article>)}{data.seatPackages.length === 0 && <p className="rounded-2xl border border-dashed border-[#CCD4E0] p-8 text-center text-sm font-bold text-[#77839A]">No seat quotes awaiting review.</p>}</div></section>
      <section className="rounded-[22px] border border-[#E0E5EF] bg-white p-5 md:p-6"><div className="flex items-center gap-3"><FileText className="text-[#B54A2A]"/><h2 className="text-2xl font-black">Payment confirmation</h2></div><p className="mt-2 text-xs leading-5 text-[#77839A]">This is a manual operational confirmation. It must be used only after CSCN verifies cleared funds outside this preview.</p><div className="mt-5 space-y-4">{data.invoices.map((invoice) => <article key={invoice.id} className="rounded-2xl border border-[#E3E7EF] p-4"><p className="text-xs font-black uppercase tracking-[.08em] text-[#77839A]">{invoice.organization.name}</p><div className="mt-2 flex items-end justify-between gap-3"><div><h3 className="font-black">{invoice.number}</h3><p className="mt-1 text-xs text-[#667085]">{invoice.seatPackage.quantity} seats · {invoice.seatPackage.program?.title || invoice.seatPackage.cohort?.program.title}</p></div><p className="font-black">{money(invoice.amount.toString(), invoice.currency)}</p></div><form action={markOrganizationInvoicePaidAction} className="mt-4"><input type="hidden" name="invoiceId" value={invoice.id}/><button className="w-full rounded-lg bg-[#137A3E] px-4 py-2.5 text-xs font-black text-white">Confirm cleared funds and activate seats</button></form></article>)}{data.invoices.length === 0 && <p className="rounded-2xl border border-dashed border-[#CCD4E0] p-8 text-center text-sm font-bold text-[#77839A]">No invoice requires payment confirmation.</p>}</div></section></div>
    <section className="rounded-[22px] border border-[#E0E5EF] bg-white p-5 md:p-6"><p className="text-xs font-black uppercase tracking-[.12em] text-[#B54A2A]">Private cohort operations</p><h2 className="mt-2 text-2xl font-black">Create an organization-only cohort</h2><p className="mt-2 max-w-3xl text-xs leading-5 text-[#77839A]">Private cohorts are excluded from the public catalog. Learners reach them only after an active organization seat is allocated.</p><form action={createOrganizationCohortAction} className="mt-5 grid gap-3 md:grid-cols-2 xl:grid-cols-4"><select name="organizationId" required className="h-10 rounded-lg border border-[#D9DFE9] px-3 text-xs"><option value="">Choose active organization</option>{data.organizations.filter((item) => item.status === "ACTIVE").map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select name="programId" required className="h-10 rounded-lg border border-[#D9DFE9] px-3 text-xs"><option value="">Choose published program</option>{data.programs.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><input name="title" required minLength={3} placeholder="Private cohort title" className="h-10 rounded-lg border border-[#D9DFE9] px-3 text-sm"/><input name="slug" required placeholder="organization-program-2027" className="h-10 rounded-lg border border-[#D9DFE9] px-3 text-sm"/><label className="grid gap-1 text-xs font-bold text-[#667085]">Starts<input name="startsAt" type="datetime-local" required className="h-10 rounded-lg border border-[#D9DFE9] px-2 text-xs font-normal text-[#071535]"/></label><label className="grid gap-1 text-xs font-bold text-[#667085]">Ends<input name="endsAt" type="datetime-local" required className="h-10 rounded-lg border border-[#D9DFE9] px-2 text-xs font-normal text-[#071535]"/></label><input name="capacity" type="number" min={1} max={500} required defaultValue={20} aria-label="Cohort capacity" className="h-10 rounded-lg border border-[#D9DFE9] px-3 text-sm"/><input name="scheduleSummary" required minLength={10} placeholder="Weekly schedule and delivery context" className="h-10 rounded-lg border border-[#D9DFE9] px-3 text-sm"/><button className="rounded-full bg-[#B54A2A] px-5 py-2.5 text-sm font-black text-white md:col-span-2 xl:col-span-4">Create private cohort</button></form></section>
  </main>;
}
