import type { Metadata } from "next";

import { createCareerOpportunityAction, setCareerOpportunityStatusAction } from "@/actions/career";
import { moderateCommunityReportAction } from "@/actions/community";
import { requireAnyAdminPermission } from "@/lib/admin-guards";
import { getAdminCommunityCareer } from "@/lib/services/career.service";

export const metadata: Metadata = { title: "Community & Career | CSCN Admin" };

export default async function AdminCommunityCareerPage() {
  await requireAnyAdminPermission(["canManageMarketing", "canManageLearners", "canManageSettings"]);
  const data = await getAdminCommunityCareer();
  return <main className="mx-auto max-w-[1600px] px-4 py-6 md:px-8"><header className="rounded-[26px] bg-[#071535] p-7 text-white"><p className="text-xs font-black uppercase tracking-[.14em] text-[#8CB0FF]">Community & Career operations</p><h1 className="mt-3 text-3xl font-black tracking-[-.045em]">Moderate learning spaces. Publish credible opportunities.</h1><div className="mt-6 grid grid-cols-3 gap-3"><div className="rounded-2xl bg-white/8 p-4"><p className="text-2xl font-black">{data.stats.spaces}</p><p className="text-xs text-[#B8C6E3]">published spaces</p></div><div className="rounded-2xl bg-white/8 p-4"><p className="text-2xl font-black">{data.stats.posts}</p><p className="text-xs text-[#B8C6E3]">published posts</p></div><div className="rounded-2xl bg-white/8 p-4"><p className="text-2xl font-black">{data.stats.discoverableTalent}</p><p className="text-xs text-[#B8C6E3]">opted-in talent</p></div></div></header>
  <div className="mt-6 grid gap-6 xl:grid-cols-2"><section className="rounded-[24px] border border-[#E1E5ED] bg-white p-5"><h2 className="text-xl font-black">Open community reports</h2><div className="mt-5 space-y-4">{data.reports.map((report) => <article key={report.id} className="rounded-2xl border border-[#E7EAF1] p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-black uppercase text-[#B42318]">{report.reason}</p><a href={`/community/${report.post.space.slug}`} className="text-xs font-black text-[#1C4ED1]">Open space</a></div><p className="mt-2 text-sm font-bold">{report.post.space.title}</p><p className="mt-2 rounded-xl bg-[#F7F8FA] p-3 text-sm leading-6 text-[#556178]">{report.post.body}</p><p className="mt-2 text-xs text-[#7B8598]">Reported by {report.reporter.name || report.reporter.email}</p><form action={moderateCommunityReportAction} className="mt-3 flex flex-wrap gap-2"><input type="hidden" name="reportId" value={report.id}/><input name="resolution" maxLength={500} placeholder="Resolution note" className="h-9 min-w-0 flex-1 rounded-lg border border-[#DCE2ED] px-3 text-xs"/><button name="decision" value="REMOVE" className="rounded-lg bg-[#B42318] px-3 text-xs font-black text-white">Remove post</button><button name="decision" value="DISMISS" className="rounded-lg border border-[#DCE2ED] px-3 text-xs font-black">Dismiss</button></form></article>)}{data.reports.length === 0 && <p className="rounded-2xl border border-dashed border-[#D7DDE7] p-8 text-center text-sm font-bold text-[#7B8598]">No open reports.</p>}</div></section>
  <section className="rounded-[24px] border border-[#E1E5ED] bg-white p-5"><h2 className="text-xl font-black">Publish an opportunity</h2><form action={createCareerOpportunityAction} className="mt-5 grid gap-3 md:grid-cols-2"><input name="company" required placeholder="Company" className="h-10 rounded-lg border border-[#DCE2ED] px-3 text-sm"/><input name="role" required placeholder="Role" className="h-10 rounded-lg border border-[#DCE2ED] px-3 text-sm"/><input name="slug" required placeholder="company-role-2026" className="h-10 rounded-lg border border-[#DCE2ED] px-3 text-sm"/><input name="location" required placeholder="Lagos, Nigeria" className="h-10 rounded-lg border border-[#DCE2ED] px-3 text-sm"/><select name="workplaceType" className="h-10 rounded-lg border border-[#DCE2ED] px-3 text-sm"><option value="REMOTE">Remote</option><option value="HYBRID">Hybrid</option><option value="ONSITE">On-site</option></select><select name="employmentType" className="h-10 rounded-lg border border-[#DCE2ED] px-3 text-sm"><option value="FULL_TIME">Full-time</option><option value="PART_TIME">Part-time</option><option value="CONTRACT">Contract</option><option value="INTERNSHIP">Internship</option><option value="FREELANCE">Freelance</option></select><select name="level" className="h-10 rounded-lg border border-[#DCE2ED] px-3 text-sm"><option value="ENTRY">Entry</option><option value="MID">Mid</option><option value="SENIOR">Senior</option><option value="ANY">Any level</option></select><input name="skills" required placeholder="Figma, Research, Prototyping" className="h-10 rounded-lg border border-[#DCE2ED] px-3 text-sm"/><input name="applicationUrl" type="url" required placeholder="https://company.com/jobs/…" className="h-10 rounded-lg border border-[#DCE2ED] px-3 text-sm"/><input name="source" required placeholder="Company careers page" className="h-10 rounded-lg border border-[#DCE2ED] px-3 text-sm"/><label className="grid gap-1 text-xs font-bold text-[#556178]"><span>Application deadline (optional)</span><input name="applicationDeadline" type="date" className="h-10 rounded-lg border border-[#DCE2ED] px-3 text-sm font-normal text-[#071535]"/></label><input name="salaryText" placeholder="Salary, if supplied" className="h-10 rounded-lg border border-[#DCE2ED] px-3 text-sm"/><textarea name="summary" required minLength={20} maxLength={240} placeholder="Short summary" className="rounded-lg border border-[#DCE2ED] p-3 text-sm md:col-span-2"/><textarea name="description" required minLength={40} maxLength={5000} rows={5} placeholder="Role details" className="rounded-lg border border-[#DCE2ED] p-3 text-sm md:col-span-2"/><button className="rounded-full bg-[#1C4ED1] px-5 py-2.5 text-sm font-black text-white md:col-span-2">Publish opportunity</button></form></section></div>
  <section className="mt-6 rounded-[24px] border border-[#E1E5ED] bg-white p-5"><h2 className="text-xl font-black">Opportunity inventory</h2><div className="mt-4 divide-y divide-[#EDF0F5]">{data.opportunities.map((item) => <div key={item.id} className="flex flex-col justify-between gap-3 py-4 md:flex-row md:items-center"><div><p className="text-sm font-black">{item.company} · {item.role}</p><p className="mt-1 text-xs text-[#7B8598]">{item.status.toLowerCase()} · {item._count.saves} saves · {item._count.interests} tracked applications</p></div><form action={setCareerOpportunityStatusAction} className="flex gap-2"><input type="hidden" name="opportunityId" value={item.id}/>{item.status !== "PUBLISHED" && <button name="status" value="PUBLISHED" className="rounded-lg border border-[#DCE2ED] px-3 py-2 text-xs font-black">Publish</button>}{item.status === "PUBLISHED" && <button name="status" value="CLOSED" className="rounded-lg border border-[#DCE2ED] px-3 py-2 text-xs font-black">Close</button>}<button name="status" value="ARCHIVED" className="rounded-lg border border-[#DCE2ED] px-3 py-2 text-xs font-black">Archive</button></form></div>)}</div></section></main>;
}
