import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, BriefcaseBusiness, Eye, EyeOff } from "lucide-react";

import { Input } from "@/components/ui/Input";
import { markOpportunityAppliedAction, updateTalentProfileAction } from "@/actions/career";
import { currentUser } from "@/lib/auth";
import { getCareerHub } from "@/lib/services/career.service";

export const metadata: Metadata = { title: "My Career Hub | CSCN" };

export default async function CareerDashboardPage({ searchParams }: { searchParams: Promise<{ careerError?: string }> }) {
  const [user, query] = await Promise.all([currentUser(), searchParams]);
  if (!user?.id) return null;
  const data = await getCareerHub({}, user.id);
  const tracked = data.opportunities.filter((item) => item.saved || item.interestStatus);
  const profile = data.talentProfile;
  return <main className="mx-auto max-w-[1500px] px-4 py-6 md:px-8"><div className="rounded-[26px] bg-[#172345] p-6 text-white md:p-9"><p className="text-xs font-black uppercase tracking-[.14em] text-[#FFCF70]">My Career Hub</p><h1 className="mt-3 text-3xl font-black tracking-[-.045em] md:text-4xl">Turn evidence into a clearer next step.</h1><p className="mt-3 max-w-2xl text-sm font-medium leading-6 text-[#C7D0E5]">Manage your talent visibility, saved roles, and application intent without making employment claims.</p></div>{query.careerError && <p className="mt-5 rounded-xl bg-[#FFF0EB] px-4 py-3 text-sm font-bold text-[#9A3412]">{query.careerError}</p>}
  <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_420px]"><section className="rounded-[24px] border border-[#E1E5ED] bg-white p-5 md:p-6"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-[.12em] text-[#1C4ED1]">Talent profile</p><h2 className="mt-2 text-2xl font-black tracking-[-.035em]">Choose what employers can discover.</h2></div>{profile?.discoverable ? <Eye className="text-[#1C4ED1]"/> : <EyeOff className="text-[#8A94A8]"/>}</div><form action={updateTalentProfileAction} className="mt-6 space-y-4"><label className="flex items-start gap-3 rounded-2xl bg-[#F6F8FC] p-4"><input type="checkbox" name="discoverable" defaultChecked={profile?.discoverable} className="mt-1 h-4 w-4 accent-[#1C4ED1]"/><span><span className="block text-sm font-black">Opt into the CSCN talent directory</span><span className="mt-1 block text-xs leading-5 text-[#68748A]">Only approved partners should receive access. Turning this off hides your talent profile.</span></span></label><label className="block text-sm font-black">Target roles<Input name="targetRoles" required defaultValue={profile?.targetRoles.join(", ")} placeholder="Product designer, Frontend engineer" className="mt-2 h-11"/></label><label className="block text-sm font-black">Skills<Input name="skills" required defaultValue={profile?.skills.join(", ")} placeholder="Figma, Research, React" className="mt-2 h-11"/></label><div className="grid gap-4 md:grid-cols-2"><label className="block text-sm font-black">Availability<Input name="availability" defaultValue={profile?.availability ?? ""} placeholder="Available from October" className="mt-2 h-11"/></label><label className="block text-sm font-black">Preferred work mode<select name="preferredWorkplace" defaultValue={profile?.preferredWorkplace ?? ""} className="mt-2 h-11 w-full rounded-xl border border-[#DCE2ED] px-3 text-sm"><option value="">No preference</option><option value="REMOTE">Remote</option><option value="HYBRID">Hybrid</option><option value="ONSITE">On-site</option></select></label></div><label className="block text-sm font-black">CV link<Input type="url" name="cvUrl" defaultValue={profile?.cvUrl ?? ""} placeholder="https://…" className="mt-2 h-11"/></label><label className="block text-sm font-black">Short career statement<textarea name="statement" maxLength={800} rows={4} defaultValue={profile?.statement ?? ""} className="mt-2 w-full rounded-xl border border-[#DCE2ED] px-4 py-3 text-sm leading-6"/></label><button className="rounded-full bg-[#1C4ED1] px-6 py-3 text-sm font-black text-white">Save career profile</button></form></section>
  <aside className="h-fit rounded-[24px] border border-[#E1E5ED] bg-white p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-black">Tracked opportunities</h2><BriefcaseBusiness className="text-[#1C4ED1]"/></div><div className="mt-5 space-y-3">{tracked.map((item) => <article key={item.id} className="rounded-2xl border border-[#E7EAF1] p-4"><p className="text-xs font-black uppercase text-[#1C4ED1]">{item.company}</p><h3 className="mt-1 text-sm font-black">{item.role}</h3><p className="mt-2 text-xs text-[#68748A]">{item.saved ? "Saved" : ""}{item.saved && item.interestStatus ? " · " : ""}{item.interestStatus ? item.interestStatus.toLowerCase() : ""}</p><div className="mt-3 flex gap-2"><a href={item.applicationUrl} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 text-xs font-black text-[#1C4ED1]">Open role <ArrowUpRight size={13}/></a>{item.interestStatus === "STARTED" && <form action={markOpportunityAppliedAction}><input type="hidden" name="opportunityId" value={item.id}/><button className="text-xs font-black text-[#217A55]">Mark applied</button></form>}</div></article>)}{tracked.length === 0 && <div className="rounded-2xl border border-dashed border-[#D7DDE7] p-6 text-center text-xs font-bold text-[#7B8598]">Saved roles and application intent will appear here.</div>}</div><Link href="/career#opportunities" className="mt-5 inline-flex text-sm font-black text-[#1C4ED1]">Browse opportunity board</Link></aside></div></main>;
}
