import { PrismaClient } from '@prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import bcrypt from 'bcryptjs';
import { config } from 'dotenv';

config({ path: '.env.local' });

const databaseUrl = process.env.DATABASE_URL ?? '';

const db = new PrismaClient({
  adapter: new PrismaPg({ connectionString: databaseUrl }),
});

const INSTRUCTORS_DATA = [
  {
    name: 'Teo Akinola',
    email: 'teo.akinola@cscn.test',
    headline: 'Co-Founder & President at Diaspora Solidarity Group',
    bio: 'Over 12 years building international non-profit projects and leading multi-disciplinary product & social impact teams.',
    location: 'Bucharest, Romania',
    countryCode: 'RO',
    slug: 'teo-akinola',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=600&auto=format&fit=crop',
    topics: ['Career Guidance', 'Social Impact', 'Product Strategy', 'Leadership'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 3,
    studentsCount: 3150,
  },
  {
    name: 'Guilherme Oliveira',
    email: 'guilherme.oliveira@cscn.test',
    headline: 'Outsystems Tech Lead & Architect at Western Union',
    bio: 'Specialized in high-scale low-code enterprise architectures and resilient cloud financial backends.',
    location: 'Lisbon, Portugal',
    countryCode: 'PT',
    slug: 'guilherme-oliveira',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop',
    topics: ['System Architecture', 'Outsystems', 'Cloud Security', 'Tech Lead Coaching'],
    free: false,
    price: 45,
    currency: 'USD',
    coursesCount: 2,
    studentsCount: 820,
  },
  {
    name: 'Tejas Pravinbhai Patel',
    email: 'tejas.patel@cscn.test',
    headline: 'Senior Software Development Engineer at Amazon',
    bio: 'Backend systems engineer with 11+ years designing distributed microservices, AWS infrastructure, and high-throughput pipelines.',
    location: 'Seattle, USA',
    countryCode: 'US',
    slug: 'tejas-patel',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&auto=format&fit=crop',
    topics: ['System Design', 'Backend Architecture', 'Amazon Interviews', 'AWS'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 4,
    studentsCount: 4890,
  },
  {
    name: 'Rishabh Gupta',
    email: 'rishabh.gupta@cscn.test',
    headline: 'Founding Product Manager at Partao',
    bio: '10 years navigating 0 to 1 product launches, user research, growth loops, and early-stage startup execution.',
    location: 'Bengaluru, India',
    countryCode: 'IN',
    slug: 'rishabh-gupta',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=600&auto=format&fit=crop',
    topics: ['Product Management', 'Startup Growth', '0 to 1 Execution', 'User Research'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 2,
    studentsCount: 1420,
  },
  {
    name: 'David Prais',
    email: 'david.prais@cscn.test',
    headline: 'CEO & Founder at PILOT ONE',
    bio: 'Serial tech entrepreneur with 15+ years in venture building, executive leadership, pitch deck strategy, and capital raising.',
    location: 'Vilnius, Lithuania',
    countryCode: 'LT',
    slug: 'david-prais',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=600&auto=format&fit=crop',
    topics: ['Founder Coaching', 'Venture Capital', 'Executive Strategy', 'Fundraising'],
    free: false,
    price: 90,
    currency: 'USD',
    coursesCount: 5,
    studentsCount: 6100,
  },
  {
    name: 'Rajeew Vishvakarma',
    email: 'rajeew.vishvakarma@cscn.test',
    headline: 'Technical Project & Product Manager at INFOSYS',
    bio: '20 years of enterprise IT leadership managing large-scale global agile transformations and cross-functional engineering teams.',
    location: 'Chicago, USA',
    countryCode: 'US',
    slug: 'rajeew-vishvakarma',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=600&auto=format&fit=crop',
    topics: ['Agile Leadership', 'Scrum Management', 'Enterprise Delivery', 'Product Operations'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 3,
    studentsCount: 2900,
  },
  {
    name: 'Shruthi Raghavendra Ph D',
    email: 'shruthi.raghavendra@cscn.test',
    headline: 'Senior Audio Research Scientist at Harman International',
    bio: 'PhD in Signal Processing & Acoustics. 11 years pioneering spatial audio algorithms, ML audio models, and consumer hardware R&D.',
    location: 'San Jose, USA',
    countryCode: 'US',
    slug: 'shruthi-raghavendra',
    image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=600&auto=format&fit=crop',
    topics: ['Audio DSP', 'AI/ML Research', 'Hardware R&D', 'PhD Career Paths'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 2,
    studentsCount: 1850,
  },
  {
    name: 'Felix Lee',
    email: 'felix.lee@cscn.test',
    headline: 'Co-Founder and CEO at ADPList',
    bio: 'Product Designer turned founder. Passionate about democratizing mentorship and empowering global creative talent.',
    location: 'San Francisco, USA',
    countryCode: 'US',
    slug: 'felix-lee',
    image: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=600&auto=format&fit=crop',
    topics: ['Design Leadership', 'Product Design', 'Startup Founder', 'Community Growth'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 6,
    studentsCount: 9500,
  },
  {
    name: 'Amara Nwosu',
    email: 'amara.nwosu@cscn.test',
    headline: 'Lead Product Designer at Flutterwave',
    bio: '8 years designing Fintech interfaces, design systems, and inclusive payment experiences across Africa & global markets.',
    location: 'Lagos, Nigeria',
    countryCode: 'NG',
    slug: 'amara-nwosu',
    image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=600&auto=format&fit=crop',
    topics: ['UI/UX Design', 'Design Systems', 'Fintech Products', 'Portfolio Critique'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 3,
    studentsCount: 3400,
  },
  {
    name: 'Elena Rostova',
    email: 'elena.rostova@cscn.test',
    headline: 'Staff AI Engineer at DeepMind',
    bio: 'Specializing in Reinforcement Learning, Transformer Models, and LLM Agentic frameworks.',
    location: 'London, UK',
    countryCode: 'UK',
    slug: 'elena-rostova',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=600&auto=format&fit=crop',
    topics: ['Artificial Intelligence', 'LLMs', 'PyTorch', 'Research Papers'],
    free: false,
    price: 60,
    currency: 'USD',
    coursesCount: 4,
    studentsCount: 5200,
  },
  {
    name: 'Marcus Vance',
    email: 'marcus.vance@cscn.test',
    headline: 'VP of Brand & Marketing at Stripe',
    bio: '14 years shaping brand narrative, product marketing strategy, and developer community outreach at hyper-growth scale.',
    location: 'New York, USA',
    countryCode: 'US',
    slug: 'marcus-vance',
    image: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?q=80&w=600&auto=format&fit=crop',
    topics: ['Brand Strategy', 'Product Marketing', 'Developer Experience', 'Go-To-Market'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 3,
    studentsCount: 2750,
  },
  {
    name: 'Chloe Bennett',
    email: 'chloe.bennett@cscn.test',
    headline: 'Senior Motion Graphic Designer at Buck',
    bio: 'Crafting 3D animations, brand identities, and commercial motion assets for leading global brands.',
    location: 'Berlin, Germany',
    countryCode: 'DE',
    slug: 'chloe-bennett',
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600&auto=format&fit=crop',
    topics: ['Motion Design', 'After Effects', '3D Animation', 'Reel Critique'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 2,
    studentsCount: 1600,
  },
  {
    name: 'Kenia Takahashi',
    email: 'kenia.takahashi@cscn.test',
    headline: 'Head of Developer Relations at Vercel',
    bio: 'Helping engineers build modern web applications with Next.js, Edge Functions, and modern frontend tooling.',
    location: 'Tokyo, Japan',
    countryCode: 'JP',
    slug: 'kenia-takahashi',
    image: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?q=80&w=600&auto=format&fit=crop',
    topics: ['Next.js', 'Frontend Architecture', 'DevRel Careers', 'React Server Components'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 5,
    studentsCount: 7800,
  },
  {
    name: 'Tunde Bakare',
    email: 'tunde.bakare@cscn.test',
    headline: 'Cyber Security Operations Lead at Microsoft',
    bio: '10 years protecting cloud infrastructure, vulnerability auditing, threat hunting, and SOC team mentorship.',
    location: 'Toronto, Canada',
    countryCode: 'CA',
    slug: 'tunde-bakare',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=600&auto=format&fit=crop',
    topics: ['Cybersecurity', 'Cloud Defense', 'Ethical Hacking', 'SOC Management'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 3,
    studentsCount: 3100,
  },
  {
    name: 'Sophia Martinez',
    email: 'sophia.martinez@cscn.test',
    headline: 'Lead UX Researcher at Spotify',
    bio: 'Qualitative & quantitative user research methods for mobile apps used by over 500 million active listeners.',
    location: 'Barcelona, Spain',
    countryCode: 'ES',
    slug: 'sophia-martinez',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=600&auto=format&fit=crop',
    topics: ['UX Research', 'Usability Testing', 'Research Synthesis', 'Design Interviews'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 2,
    studentsCount: 2100,
  },
  {
    name: 'Kwame Mensah',
    email: 'kwame.mensah@cscn.test',
    headline: 'Principal DevOps Architect at Paystack',
    bio: 'Automating CI/CD pipelines, Kubernetes clusters, and zero-downtime database deployments.',
    location: 'Accra, Ghana',
    countryCode: 'GH',
    slug: 'kwame-mensah',
    image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=600&auto=format&fit=crop',
    topics: ['DevOps', 'Kubernetes', 'Docker', 'CI/CD Pipelines'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 3,
    studentsCount: 2950,
  },
  {
    name: 'Hannah Schmidt',
    email: 'hannah.schmidt@cscn.test',
    headline: 'Creative Director at Studio Dumbar',
    bio: 'Brand identity systems, kinetic typography, and visual storytelling for international cultural and commercial clients.',
    location: 'Amsterdam, Netherlands',
    countryCode: 'NL',
    slug: 'hannah-schmidt',
    image: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=600&auto=format&fit=crop',
    topics: ['Creative Direction', 'Brand Identity', 'Typography', 'Design Systems'],
    free: false,
    price: 50,
    currency: 'USD',
    coursesCount: 4,
    studentsCount: 4100,
  },
  {
    name: 'Mateo Rossi',
    email: 'mateo.rossi@cscn.test',
    headline: 'Senior Data Scientist at Booking.com',
    bio: 'Predictive analytics, customer recommendation engines, and A/B experimentation frameworks at global scale.',
    location: 'Milan, Italy',
    countryCode: 'IT',
    slug: 'mateo-rossi',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=600&auto=format&fit=crop',
    topics: ['Data Science', 'Python Data Stack', 'A/B Testing', 'Machine Learning'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 3,
    studentsCount: 3300,
  },
  {
    name: 'Aisha Bello',
    email: 'aisha.bello@cscn.test',
    headline: 'Staff Frontend Engineer at Moniepoint',
    bio: 'React, TypeScript, performance profiling, and resilient offline-first Web apps for millions of business merchants.',
    location: 'Abuja, Nigeria',
    countryCode: 'NG',
    slug: 'aisha-bello',
    image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=600&auto=format&fit=crop',
    topics: ['React', 'TypeScript', 'Web Performance', 'Frontend Testing'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 3,
    studentsCount: 2600,
  },
  {
    name: 'Oliver Thorne',
    email: 'oliver.thorne@cscn.test',
    headline: 'Head of Growth at Revolut',
    bio: 'Data-driven growth strategies, referral marketing engines, and international expansion frameworks.',
    location: 'London, UK',
    countryCode: 'UK',
    slug: 'oliver-thorne',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=600&auto=format&fit=crop',
    topics: ['Growth Marketing', 'User Acquisition', 'Fintech Expansion', 'Metrics & Funnels'],
    free: false,
    price: 75,
    currency: 'USD',
    coursesCount: 3,
    studentsCount: 3800,
  },
  {
    name: 'Zeynep Yilmaz',
    email: 'zeynep.yilmaz@cscn.test',
    headline: 'Senior Product Designer at Getir',
    bio: 'Mobile-first design for quick-commerce apps, design systems, and rapid prototyping in high-growth environments.',
    location: 'Istanbul, Turkey',
    countryCode: 'TR',
    slug: 'zeynep-yilmaz',
    image: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=600&auto=format&fit=crop',
    topics: ['Mobile App Design', 'Figma Systems', 'Product Prototyping', 'UX Research'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 2,
    studentsCount: 1900,
  },
  {
    name: 'Lucas Silva',
    email: 'lucas.silva@cscn.test',
    headline: 'Full-Stack Technical Lead at Nubank',
    bio: 'Node.js, GraphQL, Microfrontends, and distributed financial ledger architectures in Latin America.',
    location: 'Sao Paulo, Brazil',
    countryCode: 'BR',
    slug: 'lucas-silva',
    image: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=600&auto=format&fit=crop',
    topics: ['Node.js', 'GraphQL', 'Fintech Architecture', 'Tech Leadership'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 4,
    studentsCount: 4200,
  },
  {
    name: 'Fatima Al-Mansoor',
    email: 'fatima.almansoor@cscn.test',
    headline: 'Director of AI Products at G42',
    bio: 'Building enterprise AI platforms, computer vision applications, and sovereign AI deployments in EMEA.',
    location: 'Abu Dhabi, UAE',
    countryCode: 'AE',
    slug: 'fatima-almansoor',
    image: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=600&auto=format&fit=crop',
    topics: ['AI Governance', 'Computer Vision', 'Product Management', 'Executive Leadership'],
    free: false,
    price: 100,
    currency: 'USD',
    coursesCount: 3,
    studentsCount: 3100,
  },
  {
    name: 'Siddharth Nair',
    email: 'siddharth.nair@cscn.test',
    headline: 'Principal Cloud Architect at Tech Mahindra',
    bio: 'Multi-cloud migration strategies, Azure infrastructure, Serverless microservices, and enterprise DevSecOps.',
    location: 'Mumbai, India',
    countryCode: 'IN',
    slug: 'siddharth-nair',
    image: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=600&auto=format&fit=crop',
    topics: ['Azure Cloud', 'DevSecOps', 'Cloud Architecture', 'System Resilience'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 3,
    studentsCount: 2800,
  },
  {
    name: 'Camila Rodriguez',
    email: 'camila.rodriguez@cscn.test',
    headline: 'Design Director at Globant',
    bio: 'Leading international design teams across digital transformation, design ops, and accessibility standards.',
    location: 'Buenos Aires, Argentina',
    countryCode: 'AR',
    slug: 'camila-rodriguez',
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=600&auto=format&fit=crop',
    topics: ['Design Operations', 'Accessibility', 'Design Management', 'Portfolio Review'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 2,
    studentsCount: 1750,
  },
  {
    name: 'Victor Kaelin',
    email: 'victor.kaelin@cscn.test',
    headline: 'Staff Security Engineer at Proton',
    bio: 'End-to-end encryption, cryptographic protocols, security auditing, and open-source privacy advocacy.',
    location: 'Geneva, Switzerland',
    countryCode: 'CH',
    slug: 'victor-kaelin',
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=600&auto=format&fit=crop',
    topics: ['Cryptography', 'Privacy Engineering', 'Security Audits', 'Open Source Security'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 3,
    studentsCount: 2400,
  },
  {
    name: 'Khadija Oumar',
    email: 'khadija.oumar@cscn.test',
    headline: 'Senior Product Manager at Jumia',
    bio: 'E-commerce logistics, mobile payments, and growth strategy for emerging consumer markets across Africa.',
    location: 'Casablanca, Morocco',
    countryCode: 'MA',
    slug: 'khadija-oumar',
    image: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?q=80&w=600&auto=format&fit=crop',
    topics: ['E-Commerce Strategy', 'Product Management', 'Logistics UX', 'Marketplace Growth'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 2,
    studentsCount: 1550,
  },
  {
    name: 'Benjamin Hayes',
    email: 'benjamin.hayes@cscn.test',
    headline: 'Lead Game Developer at Ubisoft',
    bio: 'Unreal Engine 5, C++ gameplay architecture, physics simulation, and real-time graphics optimization.',
    location: 'Montreal, Canada',
    countryCode: 'CA',
    slug: 'benjamin-hayes',
    image: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?q=80&w=600&auto=format&fit=crop',
    topics: ['Unreal Engine', 'C++ Game Dev', 'Gameplay Systems', 'Real-Time Graphics'],
    free: false,
    price: 40,
    currency: 'USD',
    coursesCount: 4,
    studentsCount: 3900,
  },
  {
    name: 'Nia Williams',
    email: 'nia.williams@cscn.test',
    headline: 'Head of Content & Brand Storytelling at Canva',
    bio: '11 years developing global content strategy, editorial frameworks, and viral social campaigns for creative platforms.',
    location: 'Sydney, Australia',
    countryCode: 'AU',
    slug: 'nia-williams',
    image: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?q=80&w=600&auto=format&fit=crop',
    topics: ['Content Strategy', 'Brand Storytelling', 'Editorial Management', 'Creative Writing'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 3,
    studentsCount: 3200,
  },
  {
    name: 'Arjun Mehta',
    email: 'arjun.mehta@cscn.test',
    headline: 'Principal Backend Engineer at Swiggy',
    bio: 'High-concurrency food delivery dispatch engines, Redis caching, Go microservices, and event-driven architectures.',
    location: 'Hyderabad, India',
    countryCode: 'IN',
    slug: 'arjun-mehta',
    image: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?q=80&w=600&auto=format&fit=crop',
    topics: ['Golang', 'Event-Driven Systems', 'Redis Caching', 'High Availability'],
    free: true,
    price: 0,
    currency: 'USD',
    coursesCount: 3,
    studentsCount: 2900,
  },
];

async function main() {
  console.log('🌱 Seeding 30 diverse instructors & mentors into CSCN database...');

  const password = await bcrypt.hash('MentorTestPassword!2026', 12);

  // Category for mock courses
  const category = await db.category.upsert({
    where: { slug: 'mentorship-hub' },
    create: { name: 'Mentorship & Professional Development', slug: 'mentorship-hub' },
    update: { name: 'Mentorship & Professional Development' },
  });

  for (let i = 0; i < INSTRUCTORS_DATA.length; i++) {
    const data = INSTRUCTORS_DATA[i];

    const profileData = {
      headline: data.headline,
      bio: data.bio,
      location: data.location,
      publicProfileSlug: data.slug,
      publicProfileStatus: 'PUBLIC' as const,
    };

    const instructorProfileData = {
      isEnabled: true,
      verificationStatus: 'VERIFIED' as const,
      verifiedAt: new Date(),
      isFeatured: i < 8,
      featuredOrder: i + 1,
      bio: data.bio,
    };

    const mentorProfileData = {
      isEligible: true,
      isEnabled: true,
      approvedAt: new Date(),
      isFree: data.free,
      price: data.price > 0 ? data.price : null,
      currency: data.currency,
      bio: data.bio,
      topics: data.topics,
      instructions: 'Please come prepared with your portfolio, specific questions, or project links to get maximum value from our 1:1 session.',
    };

    const user = await db.user.upsert({
      where: { email: data.email },
      create: {
        email: data.email,
        name: data.name,
        password,
        role: 'INSTRUCTOR',
        emailVerified: new Date(),
        image: data.image,
        profile: { create: profileData },
        instructorProfile: { create: instructorProfileData },
        mentorProfile: { create: mentorProfileData },
      },
      update: {
        name: data.name,
        image: data.image,
        profile: { upsert: { create: profileData, update: profileData } },
        instructorProfile: { upsert: { create: instructorProfileData, update: instructorProfileData } },
        mentorProfile: { upsert: { create: mentorProfileData, update: mentorProfileData } },
      },
    });

    // Create published courses for the instructor to establish their track record
    for (let c = 0; c < data.coursesCount; c++) {
      const courseSlug = `${data.slug}-course-${c + 1}`;
      await db.course.upsert({
        where: { slug: courseSlug },
        create: {
          slug: courseSlug,
          title: `${data.topics[c % data.topics.length]} Masterclass with ${data.name}`,
          description: `Comprehensive industry guide on ${data.topics[c % data.topics.length]} taught by ${data.name} (${data.headline}).`,
          shortDesc: `Learn ${data.topics[c % data.topics.length]} from an experienced industry mentor.`,
          price: 0,
          baseCurrency: 'USD',
          status: 'PUBLISHED',
          difficulty: c === 0 ? 'BEGINNER' : c === 1 ? 'INTERMEDIATE' : 'ADVANCED',
          instructorId: user.id,
          categoryId: category.id,
          thumbnail: data.image,
        },
        update: {
          title: `${data.topics[c % data.topics.length]} Masterclass with ${data.name}`,
          instructorId: user.id,
          status: 'PUBLISHED',
        },
      });
    }

    // Create active mentor availability slots (Weekly Mondays, Wednesdays, Fridays)
    const weekdays = [1, 3, 5]; // Mon, Wed, Fri
    for (const weekday of weekdays) {
      const existing = await db.mentorAvailability.findFirst({
        where: { mentorId: user.id, weekday },
      });

      if (!existing) {
        await db.mentorAvailability.create({
          data: {
            mentorId: user.id,
            type: 'WEEKLY',
            weekday,
            startTime: '10:00',
            endTime: '17:00',
            timezone: 'Africa/Lagos',
            sessionDuration: 30,
            bufferMinutes: 15,
            maxBookings: 5,
            status: 'ACTIVE',
          },
        });
      }
    }

    console.log(`✅ Seeded Mentor [${i + 1}/30]: ${data.name} (${data.countryCode}) - ${data.headline}`);
  }

  console.log('🎉 Successfully seeded 30 verified instructors & mentors into CSCN database!');
}

main()
  .catch((e) => {
    console.error('❌ Error seeding mentors:', e);
    process.exit(1);
  })
  .finally(async () => {
    await db.$disconnect();
  });
