import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, BriefcaseBusiness, CalendarDays, CheckCircle2, MapPin, Sparkles } from "lucide-react";

import { applyToOpportunityAction, toggleSavedOpportunityAction } from "@/actions/career";
import Button from "@/components/ui/Button";
import { EmptyState, EmptyStateDescription, EmptyStateIcon, EmptyStateTitle } from "@/components/ui/EmptyState";
import SearchField from "@/components/ui/SearchField";
import { currentUser } from "@/lib/auth";
import { getCareerHub } from "@/lib/services/career.service";

export const metadata: Metadata = { title: "Career Support for Digital & Tech Talent | CSCN", description: "Present your skills, strengthen your portfolio, attend career workshops and discover relevant opportunities." };
const label = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/^./, (char) => char.toUpperCase());

export default async function CareerPage({ searchParams }: { searchParams: Promise<{ q?: string; workplace?: string; type?: string; level?: string; careerError?: string }> }) {
  const [query, user] = await Promise.all([searchParams, currentUser()]);
  const data = await getCareerHub({ query: query.q, workplace: query.workplace, type: query.type, level: query.level }, user?.id);
  return <main className="cscn-marketing-page pb-28 pt-32"><section className="cscn-marketing-shell"><div className="cscn-marketing-card overflow-hidden lg:grid lg:grid-cols-[1.2fr_.8fr]"><div className="p-7 md:p-12 lg:p-16"><span className="cscn-marketing-eyebrow">CSCN Career Hub</span><h1 className="cscn-marketing-display mt-5 max-w-4xl">Turn what you learned into your next opportunity.</h1><p className="cscn-marketing-copy mt-6 max-w-2xl text-base md:text-lg">Present your skills, prepare for interviews, strengthen your portfolio, and discover opportunities that explain what the work actually involves.</p><div className="mt-8 flex flex-wrap gap-3"><Link href={user ? "/dashboard/career" : "/signin?callbackUrl=/dashboard/career"} className="cscn-button-primary">Build your career profile</Link><a href="#opportunities" className="cscn-button-secondary">Browse opportunities</a></div></div><div className="bg-navy p-7 text-white md:p-10"><p className="text-xs font-bold uppercase tracking-[.13em] text-[#AFC3FF]">A practical readiness loop</p><ol className="mt-7 space-y-4">{["Publish credible projects", "Improve your CV and portfolio", "Practice with mentors and workshops", "Save and track relevant opportunities"].map((item, index) => <li key={item} className="flex items-center gap-4 rounded-xl border border-white/12 bg-white/5 p-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#EAF0FF] text-sm font-bold text-primary">{index + 1}</span><span className="text-sm font-semibold">{item}</span></li>)}</ol><p className="mt-7 text-xs leading-5 text-[#C7D0E5]">CSCN does not guarantee employment. The hub helps learners present evidence and make better-informed applications.</p></div></div></section>
  <section className="cscn-marketing-shell mt-12"><div className="grid gap-5 md:grid-cols-3"><div className="cscn-marketing-card p-6"><Sparkles className="text-primary"/><h2 className="mt-5 text-lg font-semibold">Portfolio support</h2><p className="mt-2 text-sm leading-6 text-text-body">Use approved showcase work, project feedback, and mentor review to explain your decisions.</p></div><div className="cscn-marketing-card p-6"><CalendarDays className="text-primary"/><h2 className="mt-5 text-lg font-semibold">Career workshops</h2><p className="mt-2 text-sm leading-6 text-text-body">CV clinics, interview practice, portfolio walkthroughs, and freelance-readiness sessions.</p></div><div className="cscn-marketing-card p-6"><BriefcaseBusiness className="text-primary"/><h2 className="mt-5 text-lg font-semibold">Opportunity board</h2><p className="mt-2 text-sm leading-6 text-text-body">Database-backed roles with source, skills, work mode, level, and deadline.</p></div></div></section>
  {data.workshops.length > 0 && <section className="cscn-marketing-shell mt-14"><p className="cscn-marketing-eyebrow">Upcoming workshops</p><div className="mt-5 grid gap-5 md:grid-cols-2">{data.workshops.map((event) => <article key={event.id} className="rounded-[18px] bg-navy p-6 text-white"><p className="text-xs font-bold text-[#AFC3FF]">{event.startsAt.toLocaleDateString("en-NG", { weekday: "short", day: "numeric", month: "short" })} · {event.startsAt.toLocaleTimeString("en-NG", { hour: "2-digit", minute: "2-digit" })}</p><h2 className="mt-3 text-xl font-semibold">{event.title}</h2><p className="mt-2 text-sm leading-6 text-[#C7D0E5]">{event.description}</p></article>)}</div></section>}
  <section id="opportunities" className="cscn-marketing-shell mt-16"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="cscn-marketing-eyebrow">Opportunity board</p><h2 className="cscn-marketing-heading mt-3">Roles with enough context to decide.</h2></div><p className="text-sm font-semibold text-text-body">{data.opportunities.length} matching {data.opportunities.length === 1 ? "opportunity" : "opportunities"}</p></div>
    <form className="cscn-marketing-card mt-7 grid gap-3 p-4 md:grid-cols-[1fr_170px_170px_150px_auto]"><SearchField name="q" defaultValue={query.q} placeholder="Role or company" aria-label="Search opportunities" compact/><select name="workplace" defaultValue={query.workplace ?? ""} className="cscn-form-field h-10 px-3 text-sm"><option value="">Any workplace</option><option value="REMOTE">Remote</option><option value="HYBRID">Hybrid</option><option value="ONSITE">On-site</option></select><select name="type" defaultValue={query.type ?? ""} className="cscn-form-field h-10 px-3 text-sm"><option value="">Any employment</option><option value="FULL_TIME">Full-time</option><option value="CONTRACT">Contract</option><option value="INTERNSHIP">Internship</option><option value="FREELANCE">Freelance</option></select><select name="level" defaultValue={query.level ?? ""} className="cscn-form-field h-10 px-3 text-sm"><option value="">Any level</option><option value="ENTRY">Entry</option><option value="MID">Mid</option><option value="SENIOR">Senior</option></select><Button variant="navy" size="sm" rounded="full" className="h-10">Filter</Button></form>
    {query.careerError && <p className="mt-4 rounded-xl bg-[#FFF0EB] px-4 py-3 text-sm font-bold text-[#9A3412]">{query.careerError}</p>}
    <div className="mt-6 grid gap-5 lg:grid-cols-2">{data.opportunities.map((opportunity) => <article key={opportunity.id} className="cscn-marketing-card p-5 md:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.1em] text-primary">{opportunity.company}</p><h3 className="mt-2 text-2xl font-semibold tracking-[-.03em]">{opportunity.role}</h3></div>{opportunity.featured && <span className="rounded-lg bg-[#EAF0FF] px-3 py-1 text-[10px] font-bold uppercase text-primary">Featured</span>}</div><p className="mt-3 text-sm leading-6 text-text-body">{opportunity.summary}</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-semibold"><span className="inline-flex items-center gap-1 rounded-lg bg-[#F4F6FB] px-3 py-1.5"><MapPin size={12}/>{opportunity.location}</span><span className="rounded-lg bg-[#F4F6FB] px-3 py-1.5">{label(opportunity.workplaceType)}</span><span className="rounded-lg bg-[#F4F6FB] px-3 py-1.5">{label(opportunity.employmentType)}</span><span className="rounded-lg bg-[#F4F6FB] px-3 py-1.5">{label(opportunity.level)}</span></div><div className="mt-4 flex flex-wrap gap-2">{opportunity.skills.map((skill) => <span key={skill} className="rounded-lg border border-stroke px-2.5 py-1 text-[11px] font-semibold text-text-body">{skill}</span>)}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-stroke pt-4"><div><p className="text-xs font-semibold text-text-body">Source: {opportunity.source}</p>{opportunity.applicationDeadline && <p className="mt-1 text-xs font-semibold text-red-700">Apply by {opportunity.applicationDeadline.toLocaleDateString("en-NG", { day: "numeric", month: "short", year: "numeric" })}</p>}</div><div className="flex gap-2"><form action={toggleSavedOpportunityAction}><input type="hidden" name="opportunityId" value={opportunity.id}/><button className="cscn-button-secondary min-h-0 px-4 py-2 text-xs">{opportunity.saved ? "Saved" : "Save"}</button></form><form action={applyToOpportunityAction}><input type="hidden" name="opportunityId" value={opportunity.id}/><button className="cscn-button-primary min-h-0 px-4 py-2 text-xs">Apply <ArrowUpRight size={14}/></button></form></div></div></article>)}{data.opportunities.length === 0 && <EmptyState className="lg:col-span-2"><EmptyStateIcon><CheckCircle2 size={23}/></EmptyStateIcon><EmptyStateTitle>No matching opportunities</EmptyStateTitle><EmptyStateDescription>Try clearing a filter. CSCN will not fabricate roles to fill this board.</EmptyStateDescription></EmptyState>}</div>
  </section></main>;
}
