import type { Metadata } from "next";
import Link from "next/link";
import { ArrowUpRight, BriefcaseBusiness, CalendarDays, CheckCircle2, MapPin, Search, Sparkles } from "lucide-react";

import { applyToOpportunityAction, toggleSavedOpportunityAction } from "@/actions/career";
import { currentUser } from "@/lib/auth";
import { getCareerHub } from "@/lib/services/career.service";

export const metadata: Metadata = { title: "Career Support for Digital & Tech Talent | CSCN", description: "Present your skills, strengthen your portfolio, attend career workshops and discover relevant opportunities." };
const label = (value: string) => value.replaceAll("_", " ").toLowerCase().replace(/^./, (char) => char.toUpperCase());

export default async function CareerPage({ searchParams }: { searchParams: Promise<{ q?: string; workplace?: string; type?: string; level?: string; careerError?: string }> }) {
  const [query, user] = await Promise.all([searchParams, currentUser()]);
  const data = await getCareerHub({ query: query.q, workplace: query.workplace, type: query.type, level: query.level }, user?.id);
  return <main className="min-h-screen bg-[#F8F7F2] pb-28 pt-28 text-[#111B3F]"><section className="mx-auto max-w-[88rem] px-4 lg:px-6"><div className="overflow-hidden rounded-[32px] border border-[#D9D7CE] bg-[#FFFDF6] lg:grid lg:grid-cols-[1.2fr_.8fr]"><div className="p-7 md:p-12 lg:p-16"><span className="text-xs font-black uppercase tracking-[.16em] text-[#B04B28]">CSCN Career Hub</span><h1 className="mt-5 max-w-4xl text-4xl font-black leading-[1.02] tracking-[-.058em] md:text-6xl">Turn what you learned into your next opportunity.</h1><p className="mt-6 max-w-2xl text-base font-medium leading-7 text-[#626875] md:text-lg">Present your skills, prepare for interviews, strengthen your portfolio, and discover opportunities that explain what the work actually involves.</p><div className="mt-8 flex flex-wrap gap-3"><Link href={user ? "/dashboard/career" : "/signin?callbackUrl=/dashboard/career"} className="rounded-full bg-[#B04B28] px-6 py-3 text-sm font-black text-white">Build your career profile</Link><a href="#opportunities" className="rounded-full border border-[#CBC8BD] px-6 py-3 text-sm font-black">Browse opportunities</a></div></div><div className="bg-[#172345] p-7 text-white md:p-10"><p className="text-xs font-black uppercase tracking-[.13em] text-[#FFCF70]">A practical readiness loop</p><ol className="mt-7 space-y-4">{["Publish credible projects", "Improve your CV and portfolio", "Practice with mentors and workshops", "Save and track relevant opportunities"].map((item, index) => <li key={item} className="flex items-center gap-4 rounded-2xl border border-white/12 bg-white/6 p-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#FFCF70] text-sm font-black text-[#172345]">{index + 1}</span><span className="text-sm font-bold">{item}</span></li>)}</ol><p className="mt-7 text-xs leading-5 text-[#BFC9E2]">CSCN does not guarantee employment. The hub helps learners present evidence and make better-informed applications.</p></div></div></section>
  <section className="mx-auto mt-12 max-w-[88rem] px-4 lg:px-6"><div className="grid gap-4 md:grid-cols-3"><div className="rounded-[22px] border border-[#D9D7CE] bg-white p-5"><Sparkles className="text-[#B04B28]"/><h2 className="mt-5 text-lg font-black">Portfolio support</h2><p className="mt-2 text-sm leading-6 text-[#687080]">Use approved showcase work, project feedback, and mentor review to explain your decisions.</p></div><div className="rounded-[22px] border border-[#D9D7CE] bg-white p-5"><CalendarDays className="text-[#B04B28]"/><h2 className="mt-5 text-lg font-black">Career workshops</h2><p className="mt-2 text-sm leading-6 text-[#687080]">CV clinics, interview practice, portfolio walkthroughs, and freelance-readiness sessions.</p></div><div className="rounded-[22px] border border-[#D9D7CE] bg-white p-5"><BriefcaseBusiness className="text-[#B04B28]"/><h2 className="mt-5 text-lg font-black">Opportunity board</h2><p className="mt-2 text-sm leading-6 text-[#687080]">Database-backed roles with source, skills, work mode, level, and deadline.</p></div></div></section>
  {data.workshops.length > 0 && <section className="mx-auto mt-14 max-w-[88rem] px-4 lg:px-6"><p className="text-xs font-black uppercase tracking-[.14em] text-[#B04B28]">Upcoming workshops</p><div className="mt-5 grid gap-4 md:grid-cols-2">{data.workshops.map((event) => <article key={event.id} className="rounded-[22px] bg-[#172345] p-6 text-white"><p className="text-xs font-bold text-[#FFCF70]">{event.startsAt.toLocaleDateString("en-NG", { weekday: "short", day: "numeric", month: "short" })} · {event.startsAt.toLocaleTimeString("en-NG", { hour: "2-digit", minute: "2-digit" })}</p><h2 className="mt-3 text-xl font-black">{event.title}</h2><p className="mt-2 text-sm leading-6 text-[#C7D0E5]">{event.description}</p></article>)}</div></section>}
  <section id="opportunities" className="mx-auto mt-16 max-w-[88rem] px-4 lg:px-6"><div className="flex flex-col justify-between gap-3 md:flex-row md:items-end"><div><p className="text-xs font-black uppercase tracking-[.14em] text-[#B04B28]">Opportunity board</p><h2 className="mt-3 text-3xl font-black tracking-[-.045em] md:text-4xl">Roles with enough context to decide.</h2></div><p className="text-sm font-bold text-[#687080]">{data.opportunities.length} matching {data.opportunities.length === 1 ? "opportunity" : "opportunities"}</p></div>
    <form className="mt-7 grid gap-3 rounded-[22px] border border-[#D9D7CE] bg-white p-4 md:grid-cols-[1fr_170px_170px_150px_auto]"><label className="relative"><Search className="absolute left-3 top-3 text-[#8A8F99]" size={17}/><input name="q" defaultValue={query.q} placeholder="Role or company" className="h-10 w-full rounded-xl border border-[#DDDAD1] pl-10 pr-3 text-sm"/></label><select name="workplace" defaultValue={query.workplace ?? ""} className="h-10 rounded-xl border border-[#DDDAD1] px-3 text-sm"><option value="">Any workplace</option><option value="REMOTE">Remote</option><option value="HYBRID">Hybrid</option><option value="ONSITE">On-site</option></select><select name="type" defaultValue={query.type ?? ""} className="h-10 rounded-xl border border-[#DDDAD1] px-3 text-sm"><option value="">Any employment</option><option value="FULL_TIME">Full-time</option><option value="CONTRACT">Contract</option><option value="INTERNSHIP">Internship</option><option value="FREELANCE">Freelance</option></select><select name="level" defaultValue={query.level ?? ""} className="h-10 rounded-xl border border-[#DDDAD1] px-3 text-sm"><option value="">Any level</option><option value="ENTRY">Entry</option><option value="MID">Mid</option><option value="SENIOR">Senior</option></select><button className="h-10 rounded-xl bg-[#172345] px-5 text-sm font-black text-white">Filter</button></form>
    {query.careerError && <p className="mt-4 rounded-xl bg-[#FFF0EB] px-4 py-3 text-sm font-bold text-[#9A3412]">{query.careerError}</p>}
    <div className="mt-6 grid gap-4 lg:grid-cols-2">{data.opportunities.map((opportunity) => <article key={opportunity.id} className="rounded-[24px] border border-[#D9D7CE] bg-white p-5 md:p-6"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.1em] text-[#B04B28]">{opportunity.company}</p><h3 className="mt-2 text-2xl font-black tracking-[-.035em]">{opportunity.role}</h3></div>{opportunity.featured && <span className="rounded-full bg-[#FFF2C7] px-3 py-1 text-[10px] font-black uppercase text-[#6F5200]">Featured</span>}</div><p className="mt-3 text-sm leading-6 text-[#687080]">{opportunity.summary}</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold"><span className="inline-flex items-center gap-1 rounded-full bg-[#F3F2ED] px-3 py-1.5"><MapPin size={12}/>{opportunity.location}</span><span className="rounded-full bg-[#F3F2ED] px-3 py-1.5">{label(opportunity.workplaceType)}</span><span className="rounded-full bg-[#F3F2ED] px-3 py-1.5">{label(opportunity.employmentType)}</span><span className="rounded-full bg-[#F3F2ED] px-3 py-1.5">{label(opportunity.level)}</span></div><div className="mt-4 flex flex-wrap gap-2">{opportunity.skills.map((skill) => <span key={skill} className="rounded-lg border border-[#DDDAD1] px-2.5 py-1 text-[11px] font-bold text-[#606776]">{skill}</span>)}</div><div className="mt-5 flex flex-wrap items-center justify-between gap-3 border-t border-[#ECE9E0] pt-4"><div><p className="text-xs font-bold text-[#687080]">Source: {opportunity.source}</p>{opportunity.applicationDeadline && <p className="mt-1 text-xs font-bold text-[#9A3412]">Apply by {opportunity.applicationDeadline.toLocaleDateString("en-NG", { day: "numeric", month: "short", year: "numeric" })}</p>}</div><div className="flex gap-2"><form action={toggleSavedOpportunityAction}><input type="hidden" name="opportunityId" value={opportunity.id}/><button className="rounded-full border border-[#D2CFC6] px-4 py-2 text-xs font-black">{opportunity.saved ? "Saved" : "Save"}</button></form><form action={applyToOpportunityAction}><input type="hidden" name="opportunityId" value={opportunity.id}/><button className="inline-flex items-center gap-1 rounded-full bg-[#B04B28] px-4 py-2 text-xs font-black text-white">Apply <ArrowUpRight size={14}/></button></form></div></div></article>)}{data.opportunities.length === 0 && <div className="lg:col-span-2 rounded-[24px] border border-dashed border-[#CFCBC0] bg-white p-12 text-center"><CheckCircle2 className="mx-auto text-[#B04B28]"/><h3 className="mt-4 text-xl font-black">No matching opportunities</h3><p className="mt-2 text-sm text-[#687080]">Try clearing a filter. CSCN will not fabricate roles to fill this board.</p></div>}</div>
  </section></main>;
}
