import Link from "next/link";
import { ArrowRight, CalendarRange, GraduationCap, PlusCircle, UsersRound } from "lucide-react";

import { createCohortAction } from "@/actions/cohorts";
import { requireAdminPermission } from "@/lib/admin-guards";
import { getAdminCohortDirectory } from "@/lib/services/cohort-management.service";

export const metadata = { title: "Cohorts | CSCN Admin" };

const field = "h-11 w-full rounded-xl border border-[#D9E0EC] bg-white px-3 text-sm text-[#071535] outline-none transition focus:border-[#1C4ED1] focus:ring-2 focus:ring-[#1C4ED1]/10";

export default async function AdminCohortsPage({ searchParams }: { searchParams: Promise<{ success?: string; error?: string }> }) {
  await requireAdminPermission("canManageCohorts");
  const [data, query] = await Promise.all([getAdminCohortDirectory(), searchParams]);

  return (
    <main className="mx-auto max-w-[1728px] space-y-6 p-[clamp(16px,2.78vw,48px)] pb-28 font-jakarta">
      <header className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-[11px] font-black uppercase tracking-[0.18em] text-[#1C4ED1]">Learning operations</p><h1 className="mt-2 text-3xl font-black tracking-[-0.045em] text-[#071535] sm:text-4xl">Cohort control centre</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#6F7C92]">Create structured learning runs, assign the teaching team, and govern each cohort from application to graduation.</p></div><div className="flex items-center gap-2 rounded-full bg-[#EAF1FF] px-4 py-2 text-xs font-black text-[#1C4ED1]"><GraduationCap size={15}/>{data.cohorts.length} cohorts</div></header>

      {query.success || query.error ? <div role="status" className={`rounded-2xl border px-5 py-4 text-sm font-bold ${query.error ? "border-red-200 bg-red-50 text-red-800" : "border-emerald-200 bg-emerald-50 text-emerald-800"}`}>{query.error ?? query.success}</div> : null}

      <section className="rounded-[24px] border border-[#DFE5F0] bg-white shadow-[0_18px_50px_rgba(11,28,68,0.05)]"><header className="flex items-center gap-3 border-b border-[#ECF0F6] px-6 py-5"><PlusCircle className="text-[#1C4ED1]" size={20}/><div><h2 className="text-xl font-black text-[#071535]">Create a cohort draft</h2><p className="mt-1 text-xs font-semibold text-[#8290A6]">Applications remain closed until a cohort admin explicitly opens them.</p></div></header><form action={createCohortAction} className="grid gap-4 p-6 md:grid-cols-2 xl:grid-cols-4">
        <label className="grid gap-1 text-xs font-black text-[#667085]">Published Program<select name="programId" required className={field}><option value="">Choose Program</option>{data.programs.map((program) => <option key={program.id} value={program.id}>{program.school.name} — {program.title}</option>)}</select></label>
        <label className="grid gap-1 text-xs font-black text-[#667085]">Lead instructor<select name="leadInstructorId" className={field}><option value="">Assign later</option>{data.instructors.map((user) => <option key={user.id} value={user.id}>{user.name ?? user.email}</option>)}</select></label>
        <label className="grid gap-1 text-xs font-black text-[#667085]">Cohort title<input name="title" required minLength={3} placeholder="October 2026 cohort" className={field}/></label>
        <label className="grid gap-1 text-xs font-black text-[#667085]">Slug<input name="slug" placeholder="october-2026" className={field}/></label>
        <label className="grid gap-1 text-xs font-black text-[#667085]">Applications open<input name="applicationOpenAt" type="datetime-local" required className={field}/></label>
        <label className="grid gap-1 text-xs font-black text-[#667085]">Applications close<input name="applicationCloseAt" type="datetime-local" required className={field}/></label>
        <label className="grid gap-1 text-xs font-black text-[#667085]">Cohort starts<input name="startsAt" type="datetime-local" required className={field}/></label>
        <label className="grid gap-1 text-xs font-black text-[#667085]">Cohort ends<input name="endsAt" type="datetime-local" required className={field}/></label>
        <label className="grid gap-1 text-xs font-black text-[#667085]">Timezone<input name="timezone" defaultValue="Africa/Lagos" className={field}/></label>
        <label className="grid gap-1 text-xs font-black text-[#667085]">Capacity<input name="capacity" type="number" min="1" max="5000" defaultValue="50" required className={field}/></label>
        <label className="grid gap-1 text-xs font-black text-[#667085]">Price<input name="price" type="number" min="0" step="0.01" defaultValue="0" className={field}/></label>
        <label className="grid gap-1 text-xs font-black text-[#667085]">Currency<input name="currency" defaultValue="NGN" maxLength={3} className={field}/></label>
        <label className="grid gap-1 text-xs font-black text-[#667085] xl:col-span-2">Schedule summary<input name="scheduleSummary" required minLength={10} placeholder="Live classes Tuesdays and Thursdays at 6 PM WAT" className={field}/></label>
        <label className="grid gap-1 text-xs font-black text-[#667085]">Weekly rhythm<textarea name="weeklySchedule" rows={4} placeholder={'Tuesday — live class\nThursday — studio lab'} className={`${field} h-auto py-3`}/></label>
        <label className="grid gap-1 text-xs font-black text-[#667085]">Graduation guidance<textarea name="graduationRules" rows={4} placeholder={'Complete required lessons\nSubmit capstone project'} className={`${field} h-auto py-3`}/></label>
        <div className="rounded-2xl bg-[#F5F8FD] p-4 md:col-span-2 xl:col-span-4"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-black text-[#071535]">Weighted completion policy</p><p className="mt-1 text-xs text-[#7B879D]">Weights must total 100%. Zero disables a category.</p></div><label className="flex items-center gap-2 text-xs font-black text-[#42516A]"><input name="applicationRequired" type="checkbox" defaultChecked/> Application required</label></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{[["courses",30,80],["assignments",30,70],["quizzes",15,60],["attendance",15,70],["peerReviews",10,80]].map(([key, weight, minimum]) => <div key={String(key)} className="rounded-xl bg-white p-3"><p className="text-xs font-black capitalize text-[#42516A]">{String(key).replace("peerReviews", "Peer reviews")}</p><div className="mt-2 grid grid-cols-2 gap-2"><label className="text-[10px] font-bold text-[#8490A6]">Weight<input name={`${key}Weight`} type="number" min="0" max="100" defaultValue={weight} className={`${field} mt-1 h-9`}/></label><label className="text-[10px] font-bold text-[#8490A6]">Minimum<input name={`${key}Minimum`} type="number" min="0" max="100" defaultValue={minimum} className={`${field} mt-1 h-9`}/></label></div></div>)}</div><label className="mt-3 block max-w-44 text-[10px] font-bold text-[#8490A6]">Overall minimum<input name="overallMinimum" type="number" min="0" max="100" defaultValue="70" className={`${field} mt-1 h-9`}/></label></div>
        <button className="rounded-xl bg-[#1C4ED1] px-6 py-3 text-sm font-black text-white md:col-span-2 xl:col-span-4">Create cohort draft</button>
      </form></section>

      <section><div className="mb-4 flex items-center justify-between"><h2 className="text-xl font-black text-[#071535]">All cohorts</h2><p className="text-xs font-bold text-[#8490A6]">Newest start date first</p></div><div className="grid gap-4 lg:grid-cols-2 2xl:grid-cols-3">{data.cohorts.map((cohort) => <Link key={cohort.id} href={`/dashboard/admin/cohorts/${cohort.slug}`} className="group rounded-[20px] border border-[#DFE5F0] bg-white p-5 transition hover:-translate-y-0.5 hover:border-[#9FB8F5] hover:shadow-lg"><div className="flex items-start justify-between gap-4"><span className="rounded-full bg-[#EDF3FF] px-3 py-1 text-[10px] font-black uppercase tracking-[0.1em] text-[#1C4ED1]">{cohort.status.replaceAll("_", " ")}</span><ArrowRight className="text-[#A3ADBC] transition group-hover:translate-x-1 group-hover:text-[#1C4ED1]" size={18}/></div><p className="mt-5 text-[10px] font-black uppercase tracking-[0.14em] text-[#8A96AA]">{cohort.program.school.name}</p><h3 className="mt-2 text-lg font-black tracking-[-0.02em] text-[#071535]">{cohort.title}</h3><p className="mt-1 text-sm font-semibold text-[#64718A]">{cohort.program.title}</p><div className="mt-5 grid grid-cols-2 gap-3 rounded-2xl bg-[#F6F8FC] p-4 text-xs font-bold text-[#526078]"><span className="flex items-center gap-2"><UsersRound size={14}/>{cohort._count.memberships}/{cohort.capacity} members</span><span className="flex items-center gap-2"><CalendarRange size={14}/>{cohort.startsAt.toLocaleDateString("en-GB", { day: "numeric", month: "short" })}</span><span>{cohort._count.projects} assignments</span><span>{cohort._count.scheduleEvents} events</span></div></Link>)}{!data.cohorts.length ? <div className="rounded-[20px] border border-dashed border-[#C9D3E3] p-12 text-center text-sm font-semibold text-[#7B879D] lg:col-span-2 2xl:col-span-3">No cohorts yet. Create the first draft above.</div> : null}</div></section>
    </main>
  );
}
